version: "2"
services:
  web-shortener:
    build: ./web/
    expose:
      - "8081"
    ports:
      - "8081:80"
  shortener:
    build: ./shortener/
    expose:
      - "8080"
    ports:
      - "8080:8080"