CREATE TABLE SHORT_URL
(
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ALIAS varchar(50) NOT NULL,
  SHORTEN_URL varchar(200) NOT NULL,
  ORIGINAL_URL varchar(200) NOT NULL
);
CREATE UNIQUE INDEX SHORT_URL_ALIAS_UINDEX ON SHORT_URL (ALIAS)